apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sn-deployment
spec:
  selector:
    matchLabels:
      app: sn
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sn
    spec:
      containers:
      - name: sn
        image: praveenlnx/scrapneed
        ports:
        - containerPort: 80
